### ISSUE TITLE
Logo for my buisness

### ISSUE THREAD

**Issue by rakshita-arch** [rakshita-arch/verbose-succotash#1]
I need a logo but need to be different not copied from any websites
If found any plagrism the merge request will marked as "spam" or "invalid" in the review period
so make sure make it own your work only not from anywhere on the internet

**Comment by riyaku11** [comment]
I would like to work on this

**Comment by gauravmandall** [comment]
I maked a pull request please check it

**Comment by rakshita-arch** [comment]
@riyaku11 yeah sure

**Comment by rakshita-arch** [comment]
@gauravmandall wait I'll check 
If we found any plagrism note: this will marked as spam or invalid after merge the pull request
